### ISSUE TITLE
Using hansel & gretel on multiple contigs.

### ISSUE THREAD

**Issue by fwhelan** [SamStudio8/gretel#17]
Hello! Thank you so much for creating such a wonderful tool! I've installed and tested hansel & gretel on a few single contigs in my dataset. Everything is very clearly explained and easy to use- thank you!

I'm curious about whether your software can be applied to multiple contigs together, i.e. to determine haplotypes based on SNPs present across multiple contigs? Specifically, I'm interested in assigning haplotypes to a "genome" (or at least the closest approximation of one that we can obtain from metagenomic sequencing). I know that I _can_ do this but I want to be it wouldn't violate any assumptions etc. in gretel if I _did_?

Thanks!

**Comment by SamStudio8** [comment]
Hello! Thanks for your message, it's so nice to hear that you've found our software and its suitably documented for real-world use! Can you expand a little more on your question? Currently Gretel recovers haplotypes for a given `contig:start-end`, but you can do this for as many regions on your assembly as you'd like.

Are you asking if we can do this and also consider the evidence over multiple contigs simultaneously? I think this could be difficult, as the Hansel matrix is populated with co-occurring SNPs seen on reads that align to the contig in question - which means we're locked to considering evidence from one region at a time.

**Comment by fwhelan** [comment]
Hi Sam,
Yes, I'm interested in considering evidence over multiple contigs simultaneously. In theory, I could concatenate, say, 3 contigs together for input into Gretel to get a Hansel matrix with co-occurring SNPs across the data, then separate the contigs again post-Gretel. Besides the fact that this feels hacky, would it violate anything under the hood? Is there a length constraint on input into Gretel, or a length at which the haplotype predictions might begin to drop off?
Cheers,
Fiona

**Comment by SamStudio8** [comment]
Hi Fiona,
My initial thought also was that you could concat the contigs in question.
My gut tells me that this might violate our assumption in that we are
considering what are three distinct regions as if they belonged together.

Ultimately, if your sequence reads don't actually connect the three regions
together there's no evidence for Gretel to co-consider anyway, which is
probably the technical limitation that will prohibit you from trying this.
Gretel requires every adjacent SNP pair to be supported by at least one
read. I would suspect Gretel would give you an error between the last SNP
of your first contig and the first SNP of the second contig? What would
your proposed read alignment look like?

**Comment by SamStudio8** [comment]
@fwhelan Did this answer your question? Happy to discuss further!

**Comment by fwhelan** [comment]
Hi Sam (& Happy new year!),

Yes, sorry! I got halfway through a response to you yesterday then thought I should try a few things out first. You definitely answered my question and you're right in that I wouldn't expect to have any overlapping reads at the point where 2 contigs would (artificially) be joined if I simply catted them together. I tried this quickly- catting the first 3 contigs in a metagen output file I've been playing with, and sure enough Gretel errors (albeit, after a lengthy runtime and I of course can't say for certain that catting caused the error):
```
Traceback (most recent call last):
  File "/usr/local/bin/gretel", line 9, in <module>
    load_entry_point('gretel==0.0.8', 'console_scripts', 'gretel')()
  File "build/bdist.linux-x86_64/egg/gretel/cmd.py", line 123, in main
    stop = None
IndexError: list index out of range
```

So it appears I'm back to my original question: if I have a set of contigs that I am reasonably sure are from the same genome, yet they are interspersed with gaps in our sequencing efforts, is there a way that I can call haplotypes on such a set? Or can I only do so one contig at a time?

Cheers,
Fiona

**Comment by SamStudio8** [comment]
Hi Fiona,
Happy new year!

Your new error is interesting, and I don't think it is quite related to issue #14.
An `IndexError` at [L#123 of cmd.main](https://github.com/SamStudio8/gretel/blob/master/gretel/cmd.py#L123) would (seem to) indicate that the master.fa you provided with `--master` doesn't have a valid FASTA entry - is it missing the header perhaps? Perhaps your reads do have coverage after all? `Gretel` dumps a table to stdout once it has finished reading the BAM, which describes pairwise SNP coverage over the reads (the `total` column will have a 0 if the assumption is violated).

Your actual question is interesting and not a use-case I'd thought of previously. As you've said, the gaps mean that there isn't overlapping evidence for the `Hansel` matrix, so you are missing the information required to link the haplotypes across these regions together. Although in my view this isn't a problem, as my work proposes that the haplotypes of a gene across all the organisms rather than haplotypes of whole genomes are what we really should be quantifying in the metagenome.

But I appreciate if you are looking to recover whole genomes this probably isn't the answer you are looking for, but if you've got gaps in your sequence coverage I'm not sure there is much you can do other than recover haplotypes on all of your interesting regions separately - although I'm open to thoughts and suggestions! I guess in effect you'll have a sort of haplotype-level scaffold over your contigs at least?

**Comment by fwhelan** [comment]
Hi Sam,

Ah yes- I might have just made a mistake in generating my master or bam files- I will retry (I'm sure  its user error, not `Gretel`).

I'll keep mulling over it, but I agree- I think having a haplotype-level scaffold is the best option at the moment. I might come back with another question or two, but for now, you've definitely answered this one!

All the best.
