### ISSUE TITLE
Issue loading vcf file

### ISSUE THREAD

**Issue by GoneAwry** [SamStudio8/gretel#37]
Hi Sam,

I'm very curious about trying Gretel on my data but I'm having trouble loading the vcf file (same issue with the test data provided); I've tried various approaches to solve the issue but to no avail. It keeps throwing me the following error:

> Traceback (most recent call last):
>   File "/Users/#####/opt/anaconda3/bin/gretel", line 8, in <module>
>     sys.exit(main())
>   File "/Users/#####/opt/anaconda3/lib/python3.8/site-packages/gretel/cmd.py", line 69, in main
>     VCF_h = util.process_vcf(ARGS.vcf, ARGS.contig, ARGS.start, ARGS.end)
>   File "/Users/#####/opt/anaconda3/lib/python3.8/site-packages/gretel/util.py", line 389, in process_vcf
>     vcf_records = vcf.Reader(fp)
>   File "/Users/#####/opt/anaconda3/lib/python3.8/site-packages/vcf/parser.py", line 300, in __init__
>     self._parse_metainfo()
>   File "/Users/#####/opt/anaconda3/lib/python3.8/site-packages/vcf/parser.py", line 318, in _parse_metainfo
>     while line.startswith('##'):
> **TypeError: startswith first arg must be bytes or a tuple of bytes, not str**

**Comment by SamStudio8** [comment]
Hmm, this looks like a problem inside PyVCF and sounds like a Python
str/bytes problem.
Are you compressing the VCF as per the (admittedly not perfect)
instructions?
https://gretel.readthedocs.io/en/latest/protocol.html#variant-calling

**Comment by GoneAwry** [comment]
Hi Sam, thanks for the prompt reply.
Yes, I've followed the instructions to compress/index the vcf file. I've tried modifying _util.py_, using other approaches to load the vcf file, but I just bump into other problems. For example I've tried loading the file with `vcf_records = vcf.Reader(filename=vcf_path)` instead, and it threw me this error: **UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte** (which I understand means the vcf file is still gzipped).
Checked my locale (in case), checked also all dependencies, they're all installed and up to date.

**Comment by SamStudio8** [comment]
OK. The plot thickens...

I've just installed `gretel` using `pip` as per the README. I downloaded a copy of the repo and ran `pytest` which runs a basic regression test suite (https://github.com/SamStudio8/gretel/blob/master/tests/test_test.py) and I had no problems related to the VCF (or anything else, which is a good start).

Immediately I'm thinking this can't be a pyVCF problem as I've likely installed the latest as the versions are not pinned by the gretel installer. Indeed I've just installed pyVCF 0.6.8, which is the latest on pyPI (https://pypi.org/project/PyVCF/). I see from your example you're on Python 3.8 (I'm on 3.7 still), so I made a conda environment with Python 3.8 and reinstalled everything with `pip` and cannot repeat this error.

I've tried install `gretel` with conda instead, and get an `UnsatisfiableError` error if I use Python 3.7 or 3.8, which doesn't make any sense because I was under the impression the way I'd configured the `meta.yml` would cover those versions. Dropping the fixed Python version, I was able to install `gretel` through conda as per the README and run `pytest` and that seems to work OK too...! 

Just in case it was `pytest`, I navigated to the test dir and ran `gretel` manually and it seemed to be OK:

```
(gretel-37) [sam@epona data]$ python --version
Python 3.8.10
(gretel-37) [sam@epona data]$ pwd
/home/sam/git/gretel/tests/data
(gretel-37) [sam@epona data]$ gretel -s 1 -e 19 test.bam test.vcf.gz 'hoot'
[2]
[None]
[NOTE] Loaded 8 breadcrumbs from 4 bread slices.
[NOTE] Setting Gretel.L to 3
i       pos     gap     A       C       G       T       N       -       _       tot
0       0       0       0       0       0       0       0       0       4       4
1       1       1       1       1       0       2       0       0       0       4
2       2       1       1       1       0       0       0       0       0       2
3       10      8       1       1       0       0       0       0       0       2
[NOTE] *Establishing next path
[RWGT] Ratio 0.500, Removed 4.0
[NOTE] *Establishing next path
[RWGT] Ratio 0.500, Removed 2.0
[NOTE] *Establishing next path
[NOTE] Unable to select next branch from SNP 1 to 2
       By design, Gretel will attempt to recover haplotypes until a hole in the graph has been found.
       Recovery will intentionally terminate now.
```

Can I ask that you try a fresh pip/conda install and check all the versions?

**Comment by GoneAwry** [comment]
Thanks for taking time to check what might be going wrong.
I've done a fresh installation of Gretel.
```
gretel                    0.0.94             pyh864c0ab_1    bioconda
hanselx                   0.0.92                   pypi_0    pypi
```
The error I now get, using your test data (or mine), is
`AttributeError: Can't pickle local object 'load_from_bam.<locals>.bam_worker'`
which could be an issue linked to Python 3.8 (like here: https://github.com/spack/spack/issues/14102)
Unless of course it is something to do with my python environment being too messy (https://xkcd.com/1987/)...

**Comment by SamStudio8** [comment]
Eek. Not exactly a fix but if you're using conda you could try fixing
Python to say, 3.7 in a new environment:

conda create -n gretel-py37 python=3.7

That might at least rule out some Py3.8 weirdness...

Sam

**Comment by GoneAwry** [comment]
So, turns out it is indeed an issue with Python 3.8
Running Gretel in a new environment with Python 3.7 works just fine
Thanks for your help and for being so reactive!

**Comment by SamStudio8** [comment]
Sorry that it's not an actual fix but I'm glad that workaround is working!
Hope Gretel gives you some interesting results :)
