### ISSUE TITLE
Question about how to deal with missing bridges between SNPs 

### ISSUE THREAD

**Issue by gavinmdouglas** [SamStudio8/gretel#39]
Hi @SamStudio8,

Thanks for developing Hansel and Gretel - they seem like they are a much needed contribution to the metagenomics field!

I'm running into the same problem that a few others (e.g., https://github.com/SamStudio8/gretel/issues/29) have run into here as well regarding lack of bridging reads between SNPs. Specifically I keep getting variants of this error:

```
[FAIL] Unable to recover pairwise evidence concerning SNP #28 at position 316
       Gretel needs every SNP to appear on a read with at least one other SNP, at least once.
       There is no read in your data set that bridges SNP #28 with any of its neighbours.
```

This is with gretel v0.0.94. 

The data I'm working with is 100 bp reads (mix of paired and single-end) mapped to individual reference CDS sequences and I've tried using SNPs called by `gretel-snpper` as well as InStrain with varying depth cut-offs for both. In each case I run into at least one SNP where there is no pairwise evidence with another SNP.

I was wondering first if you had any other pre-processing instructions that you would recommend. I'm thinking that maybe this error is always expected to pop up to some degree with real metagenomics data with short reads and that perhaps SNPs that don't co-occur with at least one other SNP should be discarded before running gretel?

To that end I was thinking that for each gene (and independent metagenomics sample) I could prune out SNPs that would cause this error beforehand, but keep track of how many such SNPs there were, which could give an idea of how much diversity is missing from the output haplotypes. I was also thinking that I could then identify windows of SNPs overlapping in reads and then just get smaller haplotypes per gene, which I think could still be useful.

Do you think this approach sounds reasonable or would you recommend I try something else? Please let me know if there are any files or information that I can provide!

Thanks,

Gavin

**Comment by SamStudio8** [comment]
Hi Gavin,
Thanks for trying out Gretel and sorry for the delay in responding. Yes, you're right in that this is always going to be a issue in metagenomes with low diversity that are sampled with short reads. In your case no variant at the position of SNP#28 can be bridged to any next variant at the position of SNP#29.

My recommendation would be to try `gretel-snpper` which is so aggressive with SNP calling that you tend to get enough SNPs to make the algorithm viable on stubborn data sets, but you've already tried that so your only real options are those you've suggested yourself: You could either drop the gene from your analysis entirely (due to insufficient variation to recover haplotypes in whole) or recover haplotypes on either side of the unbridged region (eg. generate haplotypes for SNP positions 1-28 and 29-N).

**Comment by gavinmdouglas** [comment]
Thanks for your response and for clarifying my questions!


Cheers,

Gavin
